export const singleFormData = {
  id: "form_123",
  title: "Customer Feedback Survey",
  description: "We value your opinion. Please take a moment to share your feedback about our product and services.",
  slug: "customer-feedback-survey",
  state: "active" as const,
  version: 1,
  createdAt: "Aug 15, 2026",
  updatedAt: "Aug 27, 2026",

  // Stats
  stats: {
    totalSubmissions: 1284,
    totalViews: 8420,
    conversionRate: 15.2,
    avgTime: "2m 34s",
    lastSubmission: "2 hours ago",
    todaySubmissions: 12,
    weekSubmissions: 89,
  },

  // Form Fields (preview only)
  fields: [
    { id: "f1", type: "heading", label: "Personal Information", validation: { required: false } },
    { id: "f2", type: "text", label: "Full Name", placeholder: "Enter your full name", validation: { required: true } },
    { id: "f3", type: "email", label: "Email Address", placeholder: "you@example.com", validation: { required: true } },
    { id: "f4", type: "phone", label: "Phone Number", placeholder: "+1 (555) 000-0000", validation: { required: false } },
    { id: "f5", type: "divider", label: "", validation: { required: false } },
    { id: "f6", type: "heading", label: "Feedback", validation: { required: false } },
    { id: "f7", type: "select", label: "How did you hear about us?", placeholder: "Select an option", options: [
      { label: "Social Media", value: "social" },
      { label: "Friend / Family", value: "referral" },
      { label: "Google Search", value: "search" },
      { label: "Advertisement", value: "ad" },
    ], validation: { required: true } },
    { id: "f8", type: "rating", label: "How would you rate our service?", validation: { required: true, min: 1, max: 5 } },
    { id: "f9", type: "textarea", label: "Your Feedback", placeholder: "Tell us what you think...", validation: { required: true, min: 20 } },
    { id: "f10", type: "checkbox", label: "What features do you use?", options: [
      { label: "Form Builder", value: "builder" },
      { label: "Analytics", value: "analytics" },
      { label: "Submissions", value: "submissions" },
    ], validation: { required: false } },
    { id: "f11", type: "toggle", label: "Would you recommend us?", validation: { required: false } },
  ],

  // Submissions dropdown data
  submissions: [
    {
      id: "sub_1",
      submittedBy: "Sarah Johnson",
      email: "sarah@example.com",
      date: "Aug 27, 2026 · 2:34 PM",
      status: "new" as const,
      values: {
        "Full Name": "Sarah Johnson",
        "Email Address": "sarah@example.com",
        "Phone Number": "+1 (555) 123-4567",
        "How did you hear about us?": "Social Media",
        "How would you rate our service?": "5 stars",
        "Your Feedback": "Absolutely love the platform! The drag and drop builder is amazing.",
        "What features do you use?": "Form Builder, Analytics",
        "Would you recommend us?": "Yes",
      },
    },
    {
      id: "sub_2",
      submittedBy: "Mike Chen",
      email: "mike@example.com",
      date: "Aug 27, 2026 · 1:15 PM",
      status: "viewed" as const,
      values: {
        "Full Name": "Mike Chen",
        "Email Address": "mike@example.com",
        "Phone Number": "",
        "How did you hear about us?": "Google Search",
        "How would you rate our service?": "4 stars",
        "Your Feedback": "Great tool but would love more integrations.",
        "What features do you use?": "Form Builder, Submissions",
        "Would you recommend us?": "Yes",
      },
    },
    {
      id: "sub_3",
      submittedBy: "Emily Davis",
      email: "emily@example.com",
      date: "Aug 26, 2026 · 11:42 AM",
      status: "archived" as const,
      values: {
        "Full Name": "Emily Davis",
        "Email Address": "emily@example.com",
        "Phone Number": "+1 (555) 987-6543",
        "How did you hear about us?": "Friend / Family",
        "How would you rate our service?": "5 stars",
        "Your Feedback": "Best form builder I have ever used. Highly recommended!",
        "What features do you use?": "Form Builder, Analytics, Submissions",
        "Would you recommend us?": "Yes",
      },
    },
    {
      id: "sub_4",
      submittedBy: "Alex Turner",
      email: "alex@example.com",
      date: "Aug 26, 2026 · 9:20 AM",
      status: "new" as const,
      values: {
        "Full Name": "Alex Turner",
        "Email Address": "alex@example.com",
        "Phone Number": "",
        "How did you hear about us?": "Advertisement",
        "How would you rate our service?": "3 stars",
        "Your Feedback": "Good but the analytics could be more detailed.",
        "What features do you use?": "Form Builder",
        "Would you recommend us?": "No",
      },
    },
    {
      id: "sub_5",
      submittedBy: "Lisa Wang",
      email: "lisa@example.com",
      date: "Aug 25, 2026 · 4:55 PM",
      status: "viewed" as const,
      values: {
        "Full Name": "Lisa Wang",
        "Email Address": "lisa@example.com",
        "Phone Number": "+1 (555) 456-7890",
        "How did you hear about us?": "Social Media",
        "How would you rate our service?": "4 stars",
        "Your Feedback": "Very intuitive interface. My team loves it.",
        "What features do you use?": "Form Builder, Analytics",
        "Would you recommend us?": "Yes",
      },
    },
  ],
};