import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/Redux.provicder";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const InterFont = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "500", "600", "800"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable}  ${InterFont.variable} font-inter  h-full antialiased`}
      cz-shortcut-listen="true"
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
